"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/common/Header/page";
import UseThemeHook from "../../Hooks/UseThemeHook";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { currentTheme } = UseThemeHook()
  console.log(currentTheme, "themeinlayout")
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[${currentTheme?.background}] `} style={{ background: currentTheme?.background }}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
